### PR TITLE
Use public licence

### PR DESCRIPTION
**Pull request by danielpieczko**
Use public licence.
Update copyright notices and licence references.
Update xjsl to 0.16.2.
Fix the README content.

Fixes issue #49.

### CODE REVIEW

**Review by lucianomartin — COMMENTED** [review]
The changes look good, but I am not sure if the README changes are ok.
Michael faced a similar issue in lib_xud and he decided to avoid changing the README till we find a common solution.
I added him as reviewer of this PR, so that he can sort this issue out.

**Comment by danielpieczko** [comment]
> The changes look good, but I am not sure if the README changes are ok.

Ok that's fair - it was a bit of a guess based on looking at other README changes, so I can accept it might be wrong.

**Comment by mbanth** [comment]
The amount of time needed to complete this Pull Request is unknown as of 10:30 BST on 26 April because the Read Me file guidelines applied to library publication may require some change.

**Review by lucianomartin — APPROVED** [review]
Looks good!

**Pull request merged**
